{
    daysUntilClose: 7,
    needsMoreInfoLabel: 'more info',
    perform: false,
    closeComment: "This issue has been closed automatically because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.\n\nHappy Coding!"
}
